#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_ICON1                               116
#define IDD_TAB_COMPRESS                        120
#define IDD_TAB_EXTRACT                         121
#define IDD_TAB_SPLIT                           123
#define IDD_TAB_REMOVESOURCE                    124
#define IDR_MENU_FILTER_SIZE                    129
#define IDD_DIALOG_MAIN                         132
#define IDD_TAB_PASSWORD                        135
#define IDD_DIALOG_PROFILE_NAME                 137
#define IDD_TAB_OTHER                           139
#define IDR_MENU_ADD_ITEM                       140
#define IDR_MENU_WRITE_PASSWORD_LIST            142
#define IDD_DIALOG_ABOUT                        144
#define IDD_TAB_OUTPUT                          146
#define IDR_MENU_CREATE_SHORTCUT                153
#define IDD_TAB_FILTER                          154
#define IDD_DIALOG_CREATE_SHORTCUT              156
#define IDR_MENU_FILTER_REGEX                   159
#define IDR_MENU_LISTVIEW                       161
#define IDD_TAB_MODE                            163
#define IDD_DIALOG_LOG                          165
#define IDD_TAB_DIRECTORY                       167
#define IDD_TAB_RENAME                          170
#define IDC_EDIT_PROFILE_NAME                   1000
#define IDC_RADIO_OUTPUT_SPECIFIC_DIR           1001
#define IDC_BUTTON_PROFILE_ADD                  1002
#define IDC_CHECKBOX_FILTER_READONLY            1003
#define IDC_CHECKBOX_PASSWORD_MASK              1004
#define IDC_COMBO_PROFILE                       1005
#define IDC_BUTTON_PROFILE_SAVE                 1007
#define IDC_CHECKBOX_COMPRESS_AUTO_RENAME       1008
#define IDC_CHECKBOX_FILTER_SYSTEM              1009
#define IDC_STATIC_VERSION                      1011
#define IDC_BUTTON_PROFILE_SHORTCUT             1012
#define IDC_EDIT_EXTRACT_EXCLUDE_BASE_DIR       1013
#define IDC_BUTTON_PROFILE_REMOVE               1014
#define IDC_CHECKBOX_FILTER_HIDDEN              1015
#define IDC_CHECKBOX_OTHER_CUSTOM_PARAM         1016
#define IDC_STATIC_PROFILE_DEFAULT              1017
#define IDC_EDIT_OTHER_CUSTOM_PARAM             1018
#define IDC_LIST1                               1019
#define IDC_BUTTON_VERSION                      1020
#define IDC_CHECKBOX_FILTER_DIRECTORY           1021
#define IDC_CHECKBOX_QUIT_RECES                 1022
#define IDC_CHECKBOX_FILTER_EMPTYDIR            1023
#define IDC_CHECKBOX_FILTER_ATTRIBUTE           1024
#define IDC_TAB1                                1025
#define IDC_CHECKBOX_TOPMOST                    1026
#define IDC_RADIO_OUTPUT_SOURCE                 1027
#define IDC_RADIO_OUTPUT_DESKTOP                1028
#define IDC_RADIO_REMOVESOURCE_SAVE             1029
#define IDC_RADIO_REMOVESOURCE_RECYCLEBIN       1030
#define IDC_RADIO_REMOVESOURCE_REMOVE           1031
#define IDC_CHECKBOX_PASSWORD_NEW               1032
#define IDC_EDIT_PASSWORD_1                     1033
#define IDC_EDIT_PASSWORD_2                     1034
#define IDC_EDIT_PASSWORD_3                     1035
#define IDC_EDIT_PASSWORD_LIST                  1036
#define IDC_EDIT_PASSWORD_NEW                   1037
#define IDC_BUTTON_REMOVE                       1038
#define IDC_BUTTON_CLEAR                        1039
#define IDC_CHECKBOX_FILTER_STRING              1040
#define IDC_CHECKBOX_FILTER_SIZE_FROM           1041
#define IDC_CHECKBOX_FILTER_SIZE_TO             1042
#define IDC_CHECKBOX_FILTER_DATE_FROM           1043
#define IDC_CHECKBOX_FILTER_DATE_TO             1044
#define IDC_DATETIMEPICKER_FILTER_FROM          1045
#define IDC_DATETIMEPICKER_FILTER_TO            1046
#define IDC_EDIT_FILTER_STRING                  1047
#define IDC_BUTTON_FILTER                       4000
#define IDC_BUTTON_HELP                         4001
#define IDC_COMBO_OTHER_LIBRARY_NAME            4002
#define IDC_SPIN_EXTRACT_EXCLUDE_BASE_DIR       4003
#define IDC_STATIC_URL                          4004
#define IDM_ADD_FILE                            4005
#define IDM_ADD_PASSWORD_LIST                   4006
#define IDM_SHORTCUT_GUI_DESKTOP                4007
#define IDM_SHORTCUT_GUI_SENDTO                 4008
#define IDM_SIZE_TB                             4009
#define IDC_EDIT_VERSION                        4011
#define IDC_STATIC_LIST                         4012
#define IDM_SHORTCUT_CUI_DESKTOP                4013
#define IDM_ADD_DIR                             4014
#define IDM_OVERWRITE_PASSWORD_LIST             4015
#define IDM_SIZE_B                              4016
#define IDC_BUTTON_ADD                          4017
#define IDC_BUTTON_OTHER_LIBRARY_SETTINGS       4018
#define IDM_SHORTCUT_CUI_SENDTO                 4020
#define IDC_GROUP_COMPLETE                      4021
#define IDM_SIZE_KB                             4022
#define IDM_SIZE_MB                             4023
#define IDM_SIZE_GB                             4024
#define IDC_EDIT_FILTER_SIZE_FROM               4025
#define IDC_BUTTON_FILTER_SIZE_FROM             4026
#define IDC_EDIT_FILTER_SIZE_TO                 4027
#define IDC_BUTTON_FILTER_SIZE_TO               4028
#define IDC_COMBO_COMPRESS_COMPRESSION_TYPE     4029
#define IDC_COMBO_COMPRESS_COMPRESSION_LEVEL    4030
#define IDC_CHECKBOX_COMPRESS_EXCLUDE_BASE_DIR  4031
#define IDC_CHECKBOX_COMPRESS_PASSWORD          4032
#define IDC_CHECKBOX_COMPRESS_HEADER_ENCRYPTION 4033
#define IDC_CHECKBOX_COMPRESS_SFX               4034
#define IDC_CHECKBOX_COMPRESS_EACH_FILE         4035
#define IDC_CHECKBOX_COMPRESS_CREATE_NEW        4036
#define IDC_CHECKBOX_COMPRESS_COPY_TIMESTAMP    4037
#define IDC_CHECKBOX_EXTRACT_CREATE_DIR         4038
#define IDC_CHECKBOX_EXTRACT_DOUBLE_DIR         4039
#define IDC_CHECKBOX_EXTRACT_OMIT_TAIL_SYMBOLS  4040
#define IDC_CHECKBOX_EXTRACT_OMIT_TAIL_NUMBERS  4041
#define IDC_CHECKBOX_EXTRACT_ONLY_FILE          4042
#define IDC_CHECKBOX_EXTRACT_COPY_TIMESTAMP     4043
#define IDC_CHECKBOX_PASSWORD_LIST              4044
#define IDC_CHECKBOX_PASSWORD_INPUT             4045
#define IDC_RADIO_SPLIT_SIZE                    4046
#define IDC_RADIO_SPLIT_CHUNK                   4047
#define IDC_COMBO_SPLIT_SIZE                    4048
#define IDC_EDIT_SPLIT_SIZE                     4049
#define IDC_BUTTON_SPLIT_SIZE                   4050
#define IDC_EDIT_SPLIT_CHUNK                    4051
#define IDC_SPIN_SPLIT_CHUNK                    4052
#define IDC_RADIO_MODE_RECOMPRESS               4053
#define IDC_BUTTON_PASSWORD_OPEN_LIST           40000
#define IDC_CHECKBOX_AT_ONCE                    40000
#define IDC_CHECKBOX_COMPRESS_KEEP_EXTENSION    40000
#define IDC_CHECKBOX_DIRECTORY_SPI              40000
#define IDC_CHECKBOX_EXTRACT_DIR_TIMESTAMP      40000
#define IDC_CHECKBOX_FILTER_REGEX               40000
#define IDC_CHECKBOX_MODE_IGNORE_DIRECTORY_STRUCTURES 40000
#define IDC_COMBO_OTHER_CODEPAGE                40000
#define IDC_EDIT_LOG                            40000
#define IDC_EDIT_RENAME_STRING                  40000
#define IDC_RADIO_SHORTCUT_GUI4RECES            40000
#define IDM_LISTVIEW_SELECT                     40000
#define IDM_REGEX_DOT                           40000
#define IDC_CHECKBOX_EXTRACT_SAME_DIR           40001
#define IDC_CHECKBOX_FILTER_RECURSIVE           40001
#define IDC_CHECKBOX_GENERAL_TEST               40001
#define IDC_CHECKBOX_MODE_BACKGROUND            40001
#define IDC_COMBO_OTHER_METHOD                  40001
#define IDC_EDIT_DIRECTORY_SPI                  40001
#define IDC_EDIT_SHORTCUT_LINKPATH              40001
#define IDC_GROUP_PROCESS                       40001
#define IDC_RADIO_OUTPUT_EACH_TIME              40001
#define IDM_LISTVIEW_DESELECT                   40001
#define IDM_REGEX_ASTERISK                      40001
#define IDC_BUTTON_FILTER_REGEX                 40002
#define IDC_CHECKBOX_DIRECTORY_B2E              40002
#define IDC_CHECKBOX_MODE_LOG                   40002
#define IDC_CHECKBOX_OTHER_SFX                  40002
#define IDC_CHECKBOX_RENAME_REGEX               40002
#define IDC_RADIO_MODE_DELETE                   40002
#define IDM_LISTVIEW_ALLSELECT                  40002
#define IDM_REGEX_PLUS                          40002
#define IDC_EDIT_DIRECTORY_B2E                  40003
#define IDC_EDIT_SHORTCUT_DESCRIPTION           40003
#define IDC_RADIO_MODE_TEST                     40003
#define IDM_LISTVIEW_ALLDESELECT                40003
#define IDM_REGEX_QUESTION                      40003
#define IDC_BUTTON_RENAME_REGEX                 40004
#define IDC_CHECKBOX_RECURSIVE                  40004
#define IDC_COMBO_SHORTCUT_SHOWCMD              40004
#define IDC_EDIT_DIRECTORY_WORK                 40004
#define IDM_LISTVIEW_REMOVE                     40004
#define IDM_REGEX_BRACE                         40004
#define IDC_CHECKBOX_DIRECTORY_WORK             40005
#define IDC_RADIO_MODE_RENAME                   40005
#define IDC_RADIO_SHORTCUT_RECES                40005
#define IDM_LISTVIEW_INVERSE                    40005
#define IDM_REGEX_BRACK                         40005
#define IDC_CHECKBOX_RENAME_STRING              40006
#define IDC_EDIT_DIRECTORY_WCX                  40006
#define IDM_REGEX_NBRACK                        40006
#define IDC_BUTTON_CANCEL                       40007
#define IDC_CHECKBOX_DIRECTORY_WCX              40007
#define IDM_REGEX_PIPE                          40007
#define IDC_CHECKBOX_GENERAL_PAUSE_ERROR        40008
#define IDM_REGEX_SPACE                         40008
#define IDM_REGEX_DIGIT                         40009
#define IDM_REGEX_ESCAPE                        40010
#define IDM_REGEX_GROUP                         40011
#define IDM_REGEX_LAZY_PLUS                     40012
#define IDM_REGEX_LAZY_ASTERISK                 40013
#define IDM_REGEX_LAZY_QUESTION                 40014
#define IDM_REGEX_LAZY_BRACE                    40015
#define IDM_REGEX_CARET                         40016
#define IDM_REGEX_DOLLAR                        40017
#define IDM_REGEX_SEMICOLON                     40018
#define IDC_RADIO_MODE_EXTRACT                  40057
#define IDC_RADIO_MODE_COMPRESS                 40058
#define IDC_BUTTON_RUN                          40059
#define IDC_BUTTON_PROFILE_EDIT                 40060
#define IDC_CHECKBOX_PROFILE_DEFAULT            40061
#define IDC_BUTTON_PASSWORD_WRITE_LIST          40062
#define IDC_EDIT_COMPRESS_RUN_COMMAND           40063
#define IDC_COMBO_COMPRESS_RUN_COMMAND          40064
#define IDC_EDIT_OUTPUT_FILE                    40065
#define IDC_CHECKBOX_QUIT_GUI4RECES             40066
#define IDC_EDIT_OUTPUT_SPECIFIC_DIR            40067
#define IDC_RADIO_MODE_LIST                     40068
#define IDC_COMBO_OUTPUT_FILE                   40069
