#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_ICON1                               116
#define IDD_TAB_COMPRESS                        120
#define IDD_TAB_EXTRACT                         121
#define IDD_TAB_SPLIT                           123
#define IDD_TAB_REMOVESOURCE                    124
#define IDR_MENU_FILTER_SIZE                    129
#define IDD_DIALOG_MAIN                         132
#define IDD_TAB_PASSWORD                        135
#define IDD_DIALOG_PROFILE_NAME                 137
#define IDD_TAB_OTHER                           139
#define IDR_MENU_ADD_ITEM                       140
#define IDR_MENU_WRITE_PASSWORD_LIST            142
#define IDD_DIALOG_ABOUT                        144
#define IDD_TAB_OUTPUT                          146
#define IDR_MENU_CREATE_SHORTCUT                153
#define IDD_TAB_FILTER                          154
#define IDC_EDIT_PROFILE_NAME                   1000
#define IDC_RADIO_OUTPUT_SPECIFIC_DIR           1000
#define IDC_BUTTON_PROFILE_ADD                  1001
#define IDC_CHECKBOX_FILTER_READONLY            1001
#define IDC_CHECKBOX_PASSWORD_MASK              1001
#define IDC_COMBO_PROFILE                       1002
#define IDC_EDIT_OTHER_SPI_DIR                  1002
#define IDC_LIST_VERSION                        1002
#define IDC_BUTTON_PROFILE_SAVE                 1003
#define IDC_CHECKBOX_COMPRESS_AUTO_RENAME       1003
#define IDC_CHECKBOX_FILTER_SYSTEM              1003
#define IDC_CHECKBOX_OTHER_SPI_DIR              1003
#define IDC_STATIC_VERSION                      1003
#define IDC_BUTTON_PROFILE_SHORTCUT             1004
#define IDC_EDIT_EXTRACT_EXCLUDE_BASE_DIR       1004
#define IDC_BUTTON_PROFILE_REMOVE               1005
#define IDC_CHECKBOX_FILTER_HIDDEN              1006
#define IDC_CHECKBOX_OTHER_CUSTOM_PARAM         1006
#define IDC_STATIC_PROFILE_DEFAULT              1006
#define IDC_EDIT_OTHER_CUSTOM_PARAM             1007
#define IDC_LIST1                               1007
#define IDC_BUTTON_VERSION                      1008
#define IDC_CHECKBOX_FILTER_DIRECTORY           1009
#define IDC_CHECKBOX_QUIT_RECES                 1011
#define IDC_CHECKBOX_FILTER_EMPTYDIR            1013
#define IDC_CHECKBOX_FILTER_ATTRIBUTE           1018
#define IDC_TAB1                                1021
#define IDC_CHECKBOX_TOPMOST                    1038
#define IDC_RADIO_OUTPUT_SOURCE                 1041
#define IDC_RADIO_OUTPUT_DESKTOP                1042
#define IDC_RADIO_REMOVESOURCE_SAVE             1046
#define IDC_RADIO_REMOVESOURCE_RECYCLEBIN       1047
#define IDC_RADIO_REMOVESOURCE_REMOVE           1048
#define IDC_CHECKBOX_PASSWORD_NEW               1052
#define IDC_EDIT_PASSWORD_1                     1053
#define IDC_EDIT_PASSWORD_2                     1054
#define IDC_EDIT_PASSWORD_3                     1055
#define IDC_EDIT_PASSWORD_LIST                  1057
#define IDC_EDIT_PASSWORD_NEW                   1058
#define IDC_BUTTON_REMOVE                       1059
#define IDC_BUTTON_CLEAR                        1060
#define IDC_CHECKBOX_FILTER_STRING              1061
#define IDC_CHECKBOX_FILTER_SIZE_FROM           1062
#define IDC_CHECKBOX_FILTER_SIZE_TO             1063
#define IDC_CHECKBOX_FILTER_DATE_FROM           1064
#define IDC_CHECKBOX_FILTER_DATE_TO             1065
#define IDC_DATETIMEPICKER_FILTER_FROM          1066
#define IDC_DATETIMEPICKER_FILTER_TO            1067
#define IDC_EDIT_FILTER_STRING                  1068
#define IDC_BUTTON_FILTER                       40000
#define IDC_BUTTON_HELP                         40000
#define IDC_BUTTON_VERSION_COPY                 40000
#define IDC_COMBO_OTHER_LIBRARY_NAME            40000
#define IDC_SPIN_EXTRACT_EXCLUDE_BASE_DIR       40000
#define IDM_ADD_FILE                            40000
#define IDM_ADD_PASSWORD_LIST                   40000
#define IDM_SHORTCUT_GUI_DESKTOP                40000
#define IDM_SIZE_TB                             40000
#define IDC_CHECKBOX_OTHER_WORK_DIR             40001
#define IDM_ADD_DIR                             40001
#define IDM_OVERWRITE_PASSWORD_LIST             40001
#define IDM_SHORTCUT_CUI_DESKTOP                40001
#define IDM_SIZE_B                              40001
#define IDC_BUTTON_ADD                          40002
#define IDC_BUTTON_OTHER_LIBRARY_SETTINGS       40002
#define IDM_SHORTCUT_GUI_SENDTO                 40002
#define IDC_EDIT_OTHER_WORK_DIR                 40003
#define IDM_SHORTCUT_CUI_SENDTO                 40003
#define IDM_SIZE_KB                             40004
#define IDM_SIZE_MB                             40006
#define IDM_SIZE_GB                             40008
#define IDC_EDIT_FILTER_SIZE_FROM               40017
#define IDC_BUTTON_FILTER_SIZE_FROM             40018
#define IDC_EDIT_FILTER_SIZE_TO                 40019
#define IDC_BUTTON_FILTER_SIZE_TO               40020
#define IDC_COMBO_COMPRESS_COMPRESSION_TYPE     40025
#define IDC_COMBO_COMPRESS_COMPRESSION_LEVEL    40026
#define IDC_CHECKBOX_COMPRESS_EXCLUDE_BASE_DIR  40027
#define IDC_CHECKBOX_COMPRESS_PASSWORD          40028
#define IDC_CHECKBOX_COMPRESS_HEADER_ENCRYPTION 40029
#define IDC_CHECKBOX_COMPRESS_SFX               40030
#define IDC_CHECKBOX_COMPRESS_EACH_FILE         40031
#define IDC_CHECKBOX_COMPRESS_CREATE_NEW        40033
#define IDC_CHECKBOX_COMPRESS_COPY_TIMESTAMP    40034
#define IDC_CHECKBOX_EXTRACT_CREATE_DIR         40035
#define IDC_CHECKBOX_EXTRACT_DOUBLE_DIR         40036
#define IDC_CHECKBOX_EXTRACT_OMIT_TAIL_SYMBOLS  40039
#define IDC_CHECKBOX_EXTRACT_OMIT_TAIL_NUMBERS  40040
#define IDC_CHECKBOX_EXTRACT_ONLY_FILE          40041
#define IDC_CHECKBOX_EXTRACT_COPY_TIMESTAMP     40042
#define IDC_CHECKBOX_PASSWORD_LIST              40045
#define IDC_CHECKBOX_PASSWORD_INPUT             40046
#define IDC_RADIO_SPLIT_SIZE                    40046
#define IDC_RADIO_SPLIT_CHUNK                   40047
#define IDC_COMBO_SPLIT_SIZE                    40048
#define IDC_EDIT_SPLIT_SIZE                     40049
#define IDC_BUTTON_SPLIT_SIZE                   40050
#define IDC_EDIT_SPLIT_CHUNK                    40051
#define IDC_SPIN_SPLIT_CHUNK                    40052
#define IDC_RADIO_MODE_RECOMPRESS               40054
#define IDC_CHECKBOX_MODE_IGNORE_DIRECTORY_STRUCTURES 40058
#define IDC_RADIO_MODE_EXTRACT                  40059
#define IDC_RADIO_MODE_COMPRESS                 40060
#define IDC_BUTTON_RUN                          40061
#define IDC_BUTTON_PROFILE_EDIT                 40064
#define IDC_CHECKBOX_PROFILE_DEFAULT            40065
#define IDC_BUTTON_PASSWORD_WRITE_LIST          40066
#define IDC_EDIT_COMPRESS_RUN_COMMAND           40071
#define IDC_COMBO_COMPRESS_RUN_COMMAND          40072
#define IDC_EDIT_OUTPUT_FILE                    40072
#define IDC_CHECKBOX_QUIT_GUI4RECES             40073
#define IDC_EDIT_OUTPUT_SPECIFIC_DIR            40073
#define IDC_RADIO_MODE_LIST                     40075
#define IDC_COMBO_OUTPUT_FILE                   40076
